[2024-12-26T18:17:21.103+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T18:17:21.134+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T18:17:20.431902+00:00 [queued]>
[2024-12-26T18:17:21.146+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T18:17:20.431902+00:00 [queued]>
[2024-12-26T18:17:21.147+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-26T18:17:21.164+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_my_python_app> on 2024-12-26 18:17:20.431902+00:00
[2024-12-26T18:17:21.173+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4031) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T18:17:21.174+0000] {standard_task_runner.py:72} INFO - Started process 4032 to run task
[2024-12-26T18:17:21.177+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_python_app_dag', 'run_my_python_app', 'manual__2024-12-26T18:17:20.431902+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/dag_my-python-app.py', '--cfg-path', '/tmp/tmp1zotsze4']
[2024-12-26T18:17:21.182+0000] {standard_task_runner.py:105} INFO - Job 532: Subtask run_my_python_app
[2024-12-26T18:17:21.273+0000] {task_command.py:467} INFO - Running <TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T18:17:20.431902+00:00 [running]> on host 1484ae97611b
[2024-12-26T18:17:21.440+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_app_dag' AIRFLOW_CTX_TASK_ID='run_my_python_app' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T18:17:20.431902+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T18:17:20.431902+00:00'
[2024-12-26T18:17:21.441+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T18:17:21.502+0000] {docker.py:379} INFO - Starting docker container from image my-python-app:latest
[2024-12-26T18:17:21.856+0000] {docker.py:73} INFO - ISSO AQUI É A APLICAÇÃO RODANDO!!!!!!!!!1.
[2024-12-26T18:17:22.155+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T18:17:22.156+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_python_app_dag, task_id=run_my_python_app, run_id=manual__2024-12-26T18:17:20.431902+00:00, execution_date=20241226T181720, start_date=20241226T181721, end_date=20241226T181722
[2024-12-26T18:17:22.232+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-26T18:17:22.273+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T18:17:22.275+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
