[2024-12-27T13:25:34.489-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-27T13:25:34.517-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-27T13:20:29.844341-03:00 [queued]>
[2024-12-27T13:25:34.530-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-27T13:20:29.844341-03:00 [queued]>
[2024-12-27T13:25:34.530-0300] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-27T13:25:34.548-0300] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_my_python_app> on 2024-12-27 13:20:29.844341-03:00
[2024-12-27T13:25:34.564-0300] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3932) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-27T13:25:34.565-0300] {standard_task_runner.py:72} INFO - Started process 3933 to run task
[2024-12-27T13:25:34.565-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_python_app_dag', 'run_my_python_app', 'manual__2024-12-27T13:20:29.844341-03:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/dag_my-python-app.py', '--cfg-path', '/tmp/tmp37lpao19']
[2024-12-27T13:25:34.570-0300] {standard_task_runner.py:105} INFO - Job 340: Subtask run_my_python_app
[2024-12-27T13:25:34.664-0300] {task_command.py:467} INFO - Running <TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-27T13:20:29.844341-03:00 [running]> on host f657cc3f60f7
[2024-12-27T13:25:34.845-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_app_dag' AIRFLOW_CTX_TASK_ID='run_my_python_app' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T13:20:29.844341-03:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T13:20:29.844341-03:00'
[2024-12-27T13:25:34.846-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-27T13:25:34.907-0300] {docker.py:379} INFO - Starting docker container from image my-python-app:latest
[2024-12-27T13:25:35.308-0300] {docker.py:73} INFO - ISSO AQUI É A APLICAÇÃO RODANDO!!!!!!!!!.
[2024-12-27T13:25:35.620-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-27T13:25:35.621-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_python_app_dag, task_id=run_my_python_app, run_id=manual__2024-12-27T13:20:29.844341-03:00, execution_date=20241227T132029, start_date=20241227T132534, end_date=20241227T132535
[2024-12-27T13:25:35.663-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-27T13:25:35.701-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-27T13:25:35.703-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
