[2024-12-26T16:37:57.574-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T16:37:57.605-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:37:56.394135-03:00 [queued]>
[2024-12-26T16:37:57.618-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:37:56.394135-03:00 [queued]>
[2024-12-26T16:37:57.618-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-26T16:37:57.636-0300] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_my_python_app> on 2024-12-26 16:37:56.394135-03:00
[2024-12-26T16:37:57.649-0300] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1107) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T16:37:57.650-0300] {standard_task_runner.py:72} INFO - Started process 1108 to run task
[2024-12-26T16:37:57.649-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_python_app_dag', 'run_my_python_app', 'manual__2024-12-26T16:37:56.394135-03:00', '--job-id', '537', '--raw', '--subdir', 'DAGS_FOLDER/dag_my-python-app.py', '--cfg-path', '/tmp/tmpqgd4urux']
[2024-12-26T16:37:57.654-0300] {standard_task_runner.py:105} INFO - Job 537: Subtask run_my_python_app
[2024-12-26T16:37:57.741-0300] {task_command.py:467} INFO - Running <TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:37:56.394135-03:00 [running]> on host 1a6bcaf2dced
[2024-12-26T16:37:57.875-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_app_dag' AIRFLOW_CTX_TASK_ID='run_my_python_app' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T16:37:56.394135-03:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T16:37:56.394135-03:00'
[2024-12-26T16:37:57.876-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T16:37:57.922-0300] {docker.py:379} INFO - Starting docker container from image my-python-app:latest
[2024-12-26T16:37:58.301-0300] {docker.py:73} INFO - ISSO AQUI É A APLICAÇÃO RODANDO!!!!!!!!!1.
[2024-12-26T16:37:58.572-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T16:37:58.573-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_python_app_dag, task_id=run_my_python_app, run_id=manual__2024-12-26T16:37:56.394135-03:00, execution_date=20241226T163756, start_date=20241226T163757, end_date=20241226T163758
[2024-12-26T16:37:58.629-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-26T16:37:58.665-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T16:37:58.666-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
