[2024-12-26T16:38:51.395-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T16:38:51.430-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:38:50.923959-03:00 [queued]>
[2024-12-26T16:38:51.446-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:38:50.923959-03:00 [queued]>
[2024-12-26T16:38:51.446-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-26T16:38:51.465-0300] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_my_python_app> on 2024-12-26 16:38:50.923959-03:00
[2024-12-26T16:38:51.479-0300] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1133) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T16:38:51.480-0300] {standard_task_runner.py:72} INFO - Started process 1134 to run task
[2024-12-26T16:38:51.479-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_python_app_dag', 'run_my_python_app', 'manual__2024-12-26T16:38:50.923959-03:00', '--job-id', '538', '--raw', '--subdir', 'DAGS_FOLDER/dag_my-python-app.py', '--cfg-path', '/tmp/tmpv3cu5s9i']
[2024-12-26T16:38:51.483-0300] {standard_task_runner.py:105} INFO - Job 538: Subtask run_my_python_app
[2024-12-26T16:38:51.575-0300] {task_command.py:467} INFO - Running <TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:38:50.923959-03:00 [running]> on host 1a6bcaf2dced
[2024-12-26T16:38:51.733-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_app_dag' AIRFLOW_CTX_TASK_ID='run_my_python_app' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T16:38:50.923959-03:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T16:38:50.923959-03:00'
[2024-12-26T16:38:51.734-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T16:38:51.792-0300] {docker.py:379} INFO - Starting docker container from image my-python-app:latest
[2024-12-26T16:38:52.228-0300] {docker.py:73} INFO - ISSO AQUI É A APLICAÇÃO RODANDO!!!!!!!!!.
[2024-12-26T16:38:52.556-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T16:38:52.557-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_python_app_dag, task_id=run_my_python_app, run_id=manual__2024-12-26T16:38:50.923959-03:00, execution_date=20241226T163850, start_date=20241226T163851, end_date=20241226T163852
[2024-12-26T16:38:52.618-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-26T16:38:52.660-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T16:38:52.662-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
