[2024-12-26T16:11:58.588-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T16:11:58.619-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:11:57.854813-03:00 [queued]>
[2024-12-26T16:11:58.632-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:11:57.854813-03:00 [queued]>
[2024-12-26T16:11:58.632-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-26T16:11:58.651-0300] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_my_python_app> on 2024-12-26 16:11:57.854813-03:00
[2024-12-26T16:11:58.667-0300] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=270) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T16:11:58.668-0300] {standard_task_runner.py:72} INFO - Started process 271 to run task
[2024-12-26T16:11:58.667-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_python_app_dag', 'run_my_python_app', 'manual__2024-12-26T16:11:57.854813-03:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/dag_my-python-app.py', '--cfg-path', '/tmp/tmp7xw1f8ic']
[2024-12-26T16:11:58.671-0300] {standard_task_runner.py:105} INFO - Job 536: Subtask run_my_python_app
[2024-12-26T16:11:58.768-0300] {task_command.py:467} INFO - Running <TaskInstance: my_python_app_dag.run_my_python_app manual__2024-12-26T16:11:57.854813-03:00 [running]> on host 1a6bcaf2dced
[2024-12-26T16:11:58.927-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_app_dag' AIRFLOW_CTX_TASK_ID='run_my_python_app' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T16:11:57.854813-03:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T16:11:57.854813-03:00'
[2024-12-26T16:11:58.928-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T16:11:58.981-0300] {docker.py:379} INFO - Starting docker container from image my-python-app:latest
[2024-12-26T16:11:59.359-0300] {docker.py:73} INFO - ISSO AQUI É A APLICAÇÃO RODANDO!!!!!!!!!1.
[2024-12-26T16:11:59.686-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T16:11:59.687-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_python_app_dag, task_id=run_my_python_app, run_id=manual__2024-12-26T16:11:57.854813-03:00, execution_date=20241226T161157, start_date=20241226T161158, end_date=20241226T161159
[2024-12-26T16:11:59.726-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-26T16:11:59.769-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T16:11:59.771-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
